version: '2'

services:
  web:
    build: ./server
    command: python run.py
    ports:
      - "80:5000"
    env_file: .env
    volumes:
      - .:/myproject 
    depends_on:
      - db 

  db:
    image: jareechang/postgresql:9.4 
    ports: 
      - "50:5432"

